### PR TITLE
fixed feature #34: regression region metrics not outputted

### PR DESCRIPTION
**Pull request by greg-junkietech**
… introduced with commit f50551d where code was removed inadvertently

### CODE REVIEW

**Review by avkonst — COMMENTED** [review]
Hi. I actually asked about regions metrics in the output in the previous pr . Can we see how the change affects the output in tests? I would like to see updated output gold file.

**Comment by greg-junkietech** [comment]
thank you for asking again, I finally managed adding the appropriate tests

**Comment by greg-junkietech** [comment]
well, seems I faced platform issues that I dont understand, I couldnt reproduce the test failures locally (win64).
I had to arrange the test fixture that does indeed exhibit `std_code_complexity_cyclomatic` metric only.
@avkonst feel free to improve if you want

**Comment by avkonst** [comment]
Hi, there is an option to run test with `-g` option (as far as I remember). it will regenerate gold files as per the current tool behavior. Could you try this please?

**Comment by greg-junkietech** [comment]
> Hi, there is an option to run test with `-g` option (as far as I remember). it will regenerate gold files as per the current tool behavior. Could you try this please?

Well, sounds to be a great feature.
But basically test run just erratically as well as the `-g` feature:
- on commit [37259b9](https://github.com/metrixplusplus/metrixplusplus/pull/40/commits/37259b9fc988b51f636a8ae75c0719610018dc60)
  - `test` run locally (win64) is OK 👌 
  - `test` run on [1464733524](https://github.com/metrixplusplus/metrixplusplus/runs/1464733524) is NOK 👎 😲
  - `test -g` produces locally (win64) some new gold files 😲
      ```
        modified:   metrixpp/tests/general/test_basic/test_help_limit_default_stdout.gold.txt
        modified:   metrixpp/tests/general/test_basic/test_view_format_view_python_stdout.gold.txt
      ```
- on commit [2e1e8a4](https://github.com/metrixplusplus/metrixplusplus/pull/40/commits/2e1e8a4ebfcd83d433651e7945644aabe939dc33)
  - `test` run locally (win64) is OK 👌 
  - `test` run on [1464733524](https://github.com/metrixplusplus/metrixplusplus/runs/1464862181) is OK 👌
  - `test -g` produces locally (win64) the same new gold files 😲
      ```
        modified:   metrixpp/tests/general/test_basic/test_help_limit_default_stdout.gold.txt
        modified:   metrixpp/tests/general/test_basic/test_view_format_view_python_stdout.gold.txt
      ```
Id be happy if you can take over at that point, thx.

**Comment by greg-junkietech** [comment]
Hello @avkonst,
How do you wanna proceed, aren't you interested in merging this to get metrics export at region level working, as well as some test coverage?

**Comment by avkonst** [comment]
Hi,
Yes, I am interested in merging this. I have got this in my todo list as you left me with a task to figure out why tests are failing. Unfortunately it is extremely busy time for me before Xmas and I am going on leave till beginning of the next year. I will try to give it 15 minutes today...

**Comment by avkonst** [comment]
Tests are passing after the merge, so all good. thanks.

**Pull request merged**
