### PR TITLE
Added Halstead's metrics and Oman's maintainability indices

### PR DESCRIPTION
**Pull request by thom-sch**
Hello togehter,

I've created some modules to calculate Halstead's metrics and Oman's maintainability indices. May be it's worth to be included into metrix++.
Modules can be found under metrixpp/myext, so to run them METRIXPLUSPLUS_PATH has to be set accordingly.

Restriction:
Since I'm not familiar with C# and Java the regex-strings are only for C++ (s. halstead_base.py). 

Regards from Meerbusch
Thomas

### CODE REVIEW

**Comment by avkonst** [comment]
This is super cool. I suggest you move myext to the general ext and make it as a standard available plugin. It is ok to disable support for java and c# (I guess you can add a check in the plugin and do nothing for these languages). Also, please update the table with available plugins in the website documentation. Consider to add tests, this is quite easy and you can use existing code samples for that. Overall, I am not going to look at it closely. I assume you verified it calculates the metrics as you expect it to be.

**Comment by avkonst** [comment]
Hi @thom-sch , will you address my comment, so I could merge it?

**Comment by thom-sch** [comment]
Hi @avkonst,

I've worked on this PR only sporadically due to other work. I think I'll be able to push a (more or less) final version between Christmas and New Year.

Regards from Meerbusch
and merry Christmas

Thomas

**Comment by avkonst** [comment]
hi, thanks for the updates. Is it possible to rebase and push again to run the CI checks?

**Pull request closed without merging**
