### PR TITLE
Exclude multiple comma separated files with --ef

### PR DESCRIPTION
**Pull request by GowthamSureshKumar**
Multiple files/folders can be excluded by using the collect command with the following tag
--ef=main1.c,main2.c,src

### CODE REVIEW

**Comment by avkonst** [comment]
@prozessorkern what do you think? seems might be useful feature, but it is going to be non-backward compatible change...

**Comment by GowthamSureshKumar** [comment]
If a comma is not used, it still works for the single file/folder just like before...

**Comment by GowthamSureshKumar** [comment]
I also found a bug in the tool with respect to this --ef tag.  I am currently working on it. Once I complete it, I shall raise a PR again. :)

**Comment by prozessorkern** [comment]
Hi GowthamSureshKumar,

thanks for contributing.
You are right, an option to exclude more than one pattern would be better.
Splitting a regex pattern on "," can break the regex syntax in some cases.
My suggestion would be to allow the --ef option multiple times.
This change would be backward compatible and more robust.

See PR #28 

Would this work for you?

Can you give me some details on the bug you found with the --ef tag?

**Comment by GowthamSureshKumar** [comment]
Hi prozessorkern,
Thanks for your reply.:-) 
I have created a new pull request for the bug fix. Details are provided in the PR message.
As for this commit, the patch provided by you works but when the code base is huge and multiple source files have to be emitted across various directories this approach of running the tool multiple times becomes a time consuming process :-) 
would be happy to contribute if there are other approaches to this.

Thank you:-)

**Comment by prozessorkern** [comment]
Hi @GowthamSureshKumar 

maybe there is a misunderstanding of using the api.

You do not have to run the tool multiple times if you want to include/exclude some files or directories.
You can just append the --ef=<regex> multiple times to the same collect run.

`python metrix++.py collect --sccc --ef=doc --ef=test`

**Comment by GowthamSureshKumar** [comment]
Ah, my bad. I get it now. I had tried it in the master branch initially and it didn't work. If it works in your PR then its good for me :) I can use it.

**Pull request closed without merging**
